name: CI Tests

on:
  push:
    branches:
    - master
    - develop
    tags:
  pull_request:
  schedule:
    # run every Monday at 6am UTC
    - cron: '0 6 * * 1'

env:
  SETUP_XVFB: True  # avoid issues if something tries to open a GUI window

jobs:
  ci-tests:
    name: Tox env ${{ matrix.python }}-${{ matrix.toxenv }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.8, 3.9]
        toxenv: [test, test-alldeps, test-linetoolsdev, test-gingadev, test-astropydev, conda]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Test with tox
      run: |
        tox -e ${{ matrix.toxenv }}

  os-tests:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # set this to false for now so windows failures don't prevent macos test from finishing
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        python: [3.8, 3.9]
        toxenv: [test-alldeps]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Test with tox
      run: |
        tox -e ${{ matrix.toxenv }}

  codestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python codestyle check
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pycodestyle
    - name: Check for runtime errors using pycodestyle
      run: |
        pycodestyle pypeit --count --select=E9
